기업 상세 페이지 - CSS 수정
2-ViewMyStartup-2-FE/2-ViewMyStartup-2team-FE pull request #109
Opened 2024-10-08 08:56 UTC by annylee0723

## 이슈 번호

- close #101 

## 작업 사항
- 피그마 디자인과 동일하게 기업 상세 페이지 css 수정
- 리스트 컨텐츠 간 라인 추가, investList 추가 후 배경 생성
- 투자하기, 삭제하기 버튼 사이 라인 추가 

## 기타
investList 추가하면서 investmentInfoList 내 76번 라인에 className 추가됨

2024-10-08 15:51 UTC, taeyeonkim94 requested changes
잘하셨습니다 이름이 좀 보기 싫긴한데..이름을 생략하자니 그건 또 아닌거 같아서 ㅠㅠ 일단 merge하겠습니다

2024-10-08 15:51 UTC, taeyeonkim94 commented on src/css/InvestmentInfoList.module.css
> +  min-width: 50rem;
테이블의 scroll을 만드려면 tableContainer가 하나 필요하지 않나요?
눈에 보이는 크기는 tableContainer가 맡고 실제 테이블의 크기는 table의 크기로 조정하는걸로 알고 있어요

2024-10-08 16:13 UTC, taeyeonkim94 requested changes

2024-10-08 16:13 UTC, taeyeonkim94 commented on src/css/InvestmentInfoList.module.css
> +  min-width: 50rem;
테이블 안의 리스트 너비이기 때문에  width: 1200px, 120rem 혹은 100%겠네요 저는 개인적으로 100%를 좋아합니다 css의 미묘한 차이가 안생겨서요.
제가 생각 할 때 min-width가 필요할 때는 스크롤이 만들어질 때인데 혹시 min-width가 필요한 이유가 있을까요?
특별한 이유가 없다면 현재 스크롤은 743px 이하일 때만 생기니까 여기서 min-width는 필요없겠네요

2024-10-09 09:35 UTC, closed without merging

2024-10-09 09:36 UTC, annylee0723 commented
잘못된 브랜치명으로 클로즈, #112 PR로 재업로드 합니다