투자하기 모달과 수정하기 모달을 공통 컴포넌트로 만들기
2-ViewMyStartup-2-FE/2-ViewMyStartup-2team-FE pull request #132
Opened 2024-10-11 05:30 UTC by taeyeonkim94

## 이슈 번호

- closehttps://github.com/2-ViewMyStartup-2-FE/2-ViewMyStartup-2team-FE/issues/130

## 작업 사항
- [ ] 투자하기 모달과 수정하기 모달을 공통 컴포넌트로 만들기

## 기타
netlify : https://app.netlify.com/sites/viewmystartup/deploys/6708b801e74999f604f953c5

2024-10-11 06:01 UTC, shinji530 requested changes

2024-10-11 06:01 UTC, shinji530 commented on src/component/InvestmentForm.js
> +  const toggleImg = isVisible ? toggle : toggleOff;
이 부분 이미지가 뒤바뀌어야 할 거 같습니다! 
비밀번호가 보이지 않을 때는 눈 뜬 토글로 해두고 비밀번호가 보일 때는 눈이 감긴 토글로 해둬야 더 익숙한 거 같습니다 
수정하기 눌렀을 때 나오는 비밀번호 확인 모달은 현재 그렇게 되어있어서 통일하는 게 좋을 거 같네요!

2024-10-11 17:01 UTC, taeyeonkim94 commented on src/component/InvestmentForm.js
> +  const toggleImg = isVisible ? toggle : toggleOff;
변경했습니다.

2024-10-13 04:42 UTC, GGON123 approved these changes
고생하셨습니다!!

2024-10-13 07:33 UTC, shinji530 approved these changes
수고하셨습니다

2024-10-13 07:33 UTC, merged